// Generated by CoffeeScript 1.6.3
var app, express, http, path, routes;

express = require('express');

routes = require('./routes');

http = require('http');

path = require('path');

app = express();

app.configure(function() {
  app.set("name", "Michael Conner");
  app.set("homepage", "www.michaelpconner.com");
  app.set("email", "nordl2@pacbell.net");
  app.set("wordurl", "/download/michaelconnerCV.docx");
  app.set("pdfurl", "/download/michaelconnerCV.pdf");
  app.set("phone", "+1.510.325.2698");
  app.set('title', "" + (app.get('name')) + " — Resume");
  app.use(express.logger('dev'));
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.favicon(path.join(__dirname, '/public/img/favicon.ico')));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.use(express["static"](path.join(__dirname, '/public')));
});

app.configure('development', function() {
  return app.use(express.errorHandler());
});
//app.get('*', function(req, res) {
//  return res.redirect("http://www.willmayner.com/resume.html");
//});

app.get('/resume', routes.index);

app.get('/download/michaelconnerCV.docx', function(req, res){
  var file = __dirname + '/public/docs/michaelconnerCV.docx';
  res.download(file); // Set disposition and send it.
});

app.get('/download/michaelconnerCV.pdf', function(req, res){
  var file = __dirname + '/public/docs/michaelconnerCV.pdf';
  res.download(file); // Set disposition and send it.
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Express server listening on port " + app.get('port'));
});
